### ISSUE TITLE
Long pause after typing `std::`

### ISSUE THREAD

**Issue by nispio** [zk-phi/ac-c-headers#3]
When I type `std::` I get a long pause while the auto-complete list populates. Is there any way to avoid this pause?

**Comment by zk-phi** [comment]
Can you run the profiler to detect the function actually causing the pause?
1. M-x profiler-start
2. type std::
3. after the pause, M-x profiler-report

**Comment by nispio** [comment]
Thanks, I didn't know about the profiler before.  It looks like pretty much all of the time is being spent in the functions `semantic-analyze-possible-completions` and `semantic-analyze-current-context`, so I guess the blame does not lie with auto-complete at all.
